version: '3.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elasticsearch
    environment:
       - cluster.name=elasticsearch-default
       - bootstrap.memory_lock=true
       - discovery.type=single-node
       - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ../elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    expose:
      - "9200"
    networks:
      - "esnet"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    container_name: kibana
    # volumes:
    ports:
      - "5601:5601"
    expose:
      - "5601"
    networks:
      - "esnet"

  neo4j:
    image: neo4j:3.5.11
    container_name: neo4j
    environment:
      #- NEO4J_AUTH=neo4j/changeme
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_connector_http_listen__address=:7474
      - NEO4J_dbms_connector_https_listen__address=:6477
      - NEO4J_dbms_connector_bolt_listen__address=:7687
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_memory_heap_initial__size=4G
      - NEO4J_dbms_memory_heap_max__size=4G
      - NEO4JLABS_PLUGINS=["apoc", "graph-algorithms"]
      - NEO4J_dbms_security_auth__enabled=false
    volumes:
      - ../neo4j-3.5/plugins:/plugins
      - ../neo4j-3.5/import:/import
      - ../neo4j-3.5/data:/data
      #- ../neo4j-3.5/docker-entrypoint.sh:/docker-entrypoint.sh
    ports:
      - "7474:7474"
      - "7687:7687"
      - "6477:6477"
    networks:
      - "esnet"

  graph_disambiguator:
    image: graph_disambiguator:1.0
    container_name: graph_disambiguator
    volumes:
      - ./log.log:/graph_disambiguator/log.log
    environment:
      - ELASTICSEARCH_HOST=elasticsearch:9200
    ports:
      - "8000:8000"
    expose:
      - "8000"
    networks:
      - "esnet"
networks:
  esnet:
